import { Banks, EPack } from "./store/soundEffectsConfigSlice";

export const samples: Record<
  EPack,
  Record<
    Banks,
    Array<{
      color: string;
      sample: string;
      keyBoard: string;
    }>
  >
> = {
  Classic_808: {
    A: [
      { color: "#d7e81c", sample: "Clap.mp3", keyBoard: "1" },
      { color: "#d7e81c", sample: "Clave.mp3", keyBoard: "2" },
      { color: "#d7e81c", sample: "Conga_High.mp3", keyBoard: "3" },
      { color: "#c41492", sample: "Conga_Low.mp3", keyBoard: "q" },
      { color: "#c41492", sample: "Cow.mp3", keyBoard: "w" },
      { color: "#c41492", sample: "Rim.mp3", keyBoard: "e" },
      { color: "#1ce885", sample: "Cymb.mp3", keyBoard: "a" },
      { color: "#1ce885", sample: "Hat_2.mp3", keyBoard: "s" },
      { color: "#1ce885", sample: "Open.mp3", keyBoard: "d" },
      { color: "#3e07e3", sample: "Kick.mp3", keyBoard: "z" },
      { color: "#3e07e3", sample: "Hat_1.mp3", keyBoard: "x" },
      { color: "#3e07e3", sample: "Snare.mp3", keyBoard: "c" },
    ],
    B: [
      { color: "#d7e81c", sample: "Cow_1.mp3", keyBoard: "1" },
      { color: "#d7e81c", sample: "Cow_2.mp3", keyBoard: "2" },
      { color: "#d7e81c", sample: "Clap.mp3", keyBoard: "3" },
      { color: "#c41492", sample: "Tom_1.mp3", keyBoard: "q" },
      { color: "#c41492", sample: "Tom_2.mp3", keyBoard: "w" },
      { color: "#c41492", sample: "Tom_3.mp3", keyBoard: "e" },
      { color: "#1ce885", sample: "Cymb.mp3", keyBoard: "a" },
      { color: "#d7e81c", sample: "Hat_2.mp3", keyBoard: "s" },
      { color: "#1ce885", sample: "Open.mp3", keyBoard: "d" },
      { color: "#3e07e3", sample: "Kick.mp3", keyBoard: "z" },
      { color: "#3e07e3", sample: "Hat_1.mp3", keyBoard: "x" },
      { color: "#3e07e3", sample: "Snare.mp3", keyBoard: "c" },
    ],
  },
  Classic_909: {
    A: [
      { color: "#d7e81c", sample: "Tom_1.mp3", keyBoard: "1" },
      { color: "#d7e81c", sample: "Tom_2.mp3", keyBoard: "2" },
      { color: "#d7e81c", sample: "Tom_3.mp3", keyBoard: "3" },
      { color: "#c41492", sample: "Tom_4.mp3", keyBoard: "q" },
      { color: "#c41492", sample: "Clap.mp3", keyBoard: "w" },
      { color: "#c41492", sample: "Open.mp3", keyBoard: "e" },
      { color: "#1ce885", sample: "Crash.mp3", keyBoard: "a" },
      { color: "#1ce885", sample: "Ride.mp3", keyBoard: "s" },
      { color: "#1ce885", sample: "Rim.mp3", keyBoard: "d" },
      { color: "#3e07e3", sample: "Kick.mp3", keyBoard: "z" },
      { color: "#3e07e3", sample: "Hat.mp3", keyBoard: "x" },
      { color: "#3e07e3", sample: "Snare.mp3", keyBoard: "c" },
    ],
    B: [
      { color: "#d7e81c", sample: "Tom.mp3", keyBoard: "1" },
      { color: "#d7e81c", sample: "Ride.mp3", keyBoard: "2" },
      { color: "#d7e81c", sample: "Clap.mp3", keyBoard: "3" },
      { color: "#c41492", sample: "Open.mp3", keyBoard: "q" },
      { color: "#c41492", sample: "Open_2.mp3", keyBoard: "w" },
      { color: "#c41492", sample: "Perc.mp3", keyBoard: "e" },
      { color: "#1ce885", sample: "Crash.mp3", keyBoard: "a" },
      { color: "#d7e81c", sample: "Hat_2.mp3", keyBoard: "s" },
      { color: "#1ce885", sample: "Hat_3.mp3", keyBoard: "d" },
      { color: "#3e07e3", sample: "Kick.mp3", keyBoard: "z" },
      { color: "#3e07e3", sample: "Hat_1.mp3", keyBoard: "x" },
      { color: "#3e07e3", sample: "Snare.mp3", keyBoard: "c" },
    ],
  },
  Dirty: {
    A: [
      { color: "#d7e81c", sample: "Tom_1.mp3", keyBoard: "1" },
      { color: "#d7e81c", sample: "Tom_2.mp3", keyBoard: "2" },
      { color: "#d7e81c", sample: "Clank.mp3", keyBoard: "3" },
      { color: "#c41492", sample: "Clank_2.mp3", keyBoard: "q" },
      { color: "#c41492", sample: "Clank_3.mp3", keyBoard: "w" },
      { color: "#c41492", sample: "Clank_4.mp3", keyBoard: "e" },
      { color: "#1ce885", sample: "Perc_1.mp3", keyBoard: "a" },
      { color: "#1ce885", sample: "Hat.mp3", keyBoard: "s" },
      { color: "#1ce885", sample: "Clap.mp3", keyBoard: "d" },
      { color: "#3e07e3", sample: "Kick.mp3", keyBoard: "z" },
      { color: "#3e07e3", sample: "Kick_2.mp3", keyBoard: "x" },
      { color: "#3e07e3", sample: "Snare.mp3", keyBoard: "c" },
    ],
    B: [
      { color: "#d7e81c", sample: "Tom_1.mp3", keyBoard: "1" },
      { color: "#d7e81c", sample: "Tom_2.mp3", keyBoard: "2" },
      { color: "#d7e81c", sample: "Tom_3.mp3", keyBoard: "3" },
      { color: "#c41492", sample: "Perc.mp3", keyBoard: "q" },
      { color: "#c41492", sample: "Perc_2.mp3", keyBoard: "w" },
      { color: "#c41492", sample: "Perc_3.mp3", keyBoard: "e" },
      { color: "#1ce885", sample: "Clap.mp3", keyBoard: "a" },
      { color: "#d7e81c", sample: "Pre.mp3", keyBoard: "s" },
      { color: "#1ce885", sample: "Open.mp3", keyBoard: "d" },
      { color: "#3e07e3", sample: "Kick.mp3", keyBoard: "z" },
      { color: "#3e07e3", sample: "Hat.mp3", keyBoard: "x" },
      { color: "#3e07e3", sample: "Snare.mp3", keyBoard: "c" },
    ],
  },
  Memphis: {
    A: [
      { color: "#d7e81c", sample: "Cow.mp3", keyBoard: "1" },
      { color: "#d7e81c", sample: "Perc_1.mp3", keyBoard: "2" },
      { color: "#d7e81c", sample: "Vbraslap.mp3", keyBoard: "3" },
      { color: "#c41492", sample: "Rim.mp3", keyBoard: "q" },
      { color: "#c41492", sample: "Shaker.mp3", keyBoard: "w" },
      { color: "#c41492", sample: "Tamb.mp3", keyBoard: "e" },
      { color: "#1ce885", sample: "Cymb.mp3", keyBoard: "a" },
      { color: "#1ce885", sample: "Hat_2.mp3", keyBoard: "s" },
      { color: "#1ce885", sample: "Clap.mp3", keyBoard: "d" },
      { color: "#3e07e3", sample: "Kick.mp3", keyBoard: "z" },
      { color: "#3e07e3", sample: "Hat_1.mp3", keyBoard: "x" },
      { color: "#3e07e3", sample: "Snare.mp3", keyBoard: "c" },
    ],
    B: [
      { color: "#d7e81c", sample: "Cow_1.mp3", keyBoard: "1" },
      { color: "#d7e81c", sample: "Cow_2.mp3", keyBoard: "2" },
      { color: "#d7e81c", sample: "Cow_3.mp3", keyBoard: "3" },
      { color: "#c41492", sample: "Cow_4.mp3", keyBoard: "q" },
      { color: "#c41492", sample: "Christmas.mp3", keyBoard: "w" },
      { color: "#c41492", sample: "Perc.mp3", keyBoard: "e" },
      { color: "#1ce885", sample: "Cymb.mp3", keyBoard: "a" },
      { color: "#d7e81c", sample: "Hat_2.mp3", keyBoard: "s" },
      { color: "#1ce885", sample: "Open.mp3", keyBoard: "d" },
      { color: "#3e07e3", sample: "Kick.mp3", keyBoard: "z" },
      { color: "#3e07e3", sample: "Hat_1.mp3", keyBoard: "x" },
      { color: "#3e07e3", sample: "Snare.mp3", keyBoard: "c" },
    ],
  },
  Phonk: {
    A: [
      { color: "#d7e81c", sample: "Cow_1.mp3", keyBoard: "1" },
      { color: "#d7e81c", sample: "Cow_2.mp3", keyBoard: "2" },
      { color: "#d7e81c", sample: "Cow_3.mp3", keyBoard: "3" },
      { color: "#c41492", sample: "Cow_4.mp3", keyBoard: "q" },
      { color: "#c41492", sample: "Perc_1.mp3", keyBoard: "w" },
      { color: "#c41492", sample: "Perc_2.mp3", keyBoard: "e" },
      { color: "#1ce885", sample: "Cymb.mp3", keyBoard: "a" },
      { color: "#1ce885", sample: "Hat_2.mp3", keyBoard: "s" },
      { color: "#1ce885", sample: "Open.mp3", keyBoard: "d" },
      { color: "#3e07e3", sample: "Kick.mp3", keyBoard: "z" },
      { color: "#3e07e3", sample: "Hat_1.mp3", keyBoard: "x" },
      { color: "#3e07e3", sample: "Snare.mp3", keyBoard: "c" },
    ],
    B: [
      { color: "#d7e81c", sample: "Cow_1.mp3", keyBoard: "1" },
      { color: "#d7e81c", sample: "Cow_2.mp3", keyBoard: "2" },
      { color: "#d7e81c", sample: "Cow_3.mp3", keyBoard: "3" },
      { color: "#c41492", sample: "Christmas.mp3", keyBoard: "q" },
      { color: "#c41492", sample: "Conga.mp3", keyBoard: "w" },
      { color: "#c41492", sample: "Rim.mp3", keyBoard: "e" },
      { color: "#1ce885", sample: "Cymb.mp3", keyBoard: "a" },
      { color: "#d7e81c", sample: "Hat_2.mp3", keyBoard: "s" },
      { color: "#1ce885", sample: "Open.mp3", keyBoard: "d" },
      { color: "#3e07e3", sample: "Kick.mp3", keyBoard: "z" },
      { color: "#3e07e3", sample: "Hat_1.mp3", keyBoard: "x" },
      { color: "#3e07e3", sample: "Snare.mp3", keyBoard: "c" },
    ],
  },
  Synthwave: {
    A: [
      { color: "#d7e81c", sample: "Tom_1.mp3", keyBoard: "1" },
      { color: "#d7e81c", sample: "Tom_2.mp3", keyBoard: "2" },
      { color: "#d7e81c", sample: "Tom_3.mp3", keyBoard: "3" },
      { color: "#c41492", sample: "Tom_4.mp3", keyBoard: "q" },
      { color: "#c41492", sample: "Perc_1.mp3", keyBoard: "w" },
      { color: "#c41492", sample: "Perc_2.mp3", keyBoard: "e" },
      { color: "#1ce885", sample: "Cymb.mp3", keyBoard: "a" },
      { color: "#1ce885", sample: "Clap.mp3", keyBoard: "s" },
      { color: "#1ce885", sample: "Perc_3.mp3", keyBoard: "d" },
      { color: "#3e07e3", sample: "Kick.mp3", keyBoard: "z" },
      { color: "#3e07e3", sample: "Hat_1.mp3", keyBoard: "x" },
      { color: "#3e07e3", sample: "Snare.mp3", keyBoard: "c" },
    ],
    B: [
      { color: "#d7e81c", sample: "Perc_1.mp3", keyBoard: "1" },
      { color: "#d7e81c", sample: "Perc_2.mp3", keyBoard: "2" },
      { color: "#d7e81c", sample: "Perc_3.mp3", keyBoard: "3" },
      { color: "#c41492", sample: "Perc_4.mp3", keyBoard: "q" },
      { color: "#c41492", sample: "Bell.mp3", keyBoard: "w" },
      { color: "#c41492", sample: "Shaker.mp3", keyBoard: "e" },
      { color: "#1ce885", sample: "Cymb.mp3", keyBoard: "a" },
      { color: "#d7e81c", sample: "Tamb.mp3", keyBoard: "s" },
      { color: "#1ce885", sample: "Hat_2.mp3", keyBoard: "d" },
      { color: "#3e07e3", sample: "Kick.mp3", keyBoard: "z" },
      { color: "#3e07e3", sample: "Hat_1.mp3", keyBoard: "x" },
      { color: "#3e07e3", sample: "Snare.mp3", keyBoard: "c" },
    ],
  },
};
