import { EInstrument } from "./store/soundEffectsConfigSlice";
import { IPad } from "./types";

export const samples: Record<
  EInstrument,
  Record<
    string,
    {
      A: IPad[];
      B: IPad[];
    }
  >
> = {
  Drums: {
    DrumMachines: {
      A: [
        { color: "#bd28d7", sample: "Cymb.mp3", keyBoard: "1" },
        { color: "#bd28d7", sample: "Tom1.mp3", keyBoard: "2" },
        { color: "#bd28d7", sample: "Tom2.mp3", keyBoard: "3" },
        { color: "#dc6123", sample: "Clave.mp3", keyBoard: "q" },
        { color: "#dc6123", sample: "Cow.mp3", keyBoard: "w" },
        { color: "#dc6123", sample: "Clap.mp3", keyBoard: "e" },
        { color: "#40db24", sample: "Maracas.mp3", keyBoard: "a" },
        { color: "#40db24", sample: "Open.mp3", keyBoard: "s" },
        { color: "#40db24", sample: "Rim.mp3", keyBoard: "d" },
        { color: "#219dde", sample: "Kick.mp3", keyBoard: "z" },
        { color: "#219dde", sample: "Hat1.mp3", keyBoard: "x" },
        { color: "#219dde", sample: "Snare.mp3", keyBoard: "c" },
      ],
      B: [
        { color: "#bd28d7", sample: "Tom1.mp3", keyBoard: "1" },
        { color: "#bd28d7", sample: "Tom1.mp3", keyBoard: "2" },
        { color: "#bd28d7", sample: "Tom2.mp3", keyBoard: "3" },
        { color: "#dc6123", sample: "Cymb.mp3", keyBoard: "q" },
        { color: "#dc6123", sample: "Perc.mp3", keyBoard: "w" },
        { color: "#dc6123", sample: "Clap.mp3", keyBoard: "e" },
        { color: "#40db24", sample: "Ride.mp3", keyBoard: "a" },
        { color: "#40db24", sample: "Open.mp3", keyBoard: "s" },
        { color: "#40db24", sample: "Rim.mp3", keyBoard: "d" },
        { color: "#219dde", sample: "Kick.mp3", keyBoard: "z" },
        { color: "#219dde", sample: "Hat1.mp3", keyBoard: "x" },
        { color: "#219dde", sample: "Snare.mp3", keyBoard: "c" },
      ],
    },
    Acoustic_Drums: {
      A: [
        { color: "#bd28d7", sample: "Tom1.mp3", keyBoard: "1" },
        { color: "#bd28d7", sample: "Tom2.mp3", keyBoard: "2" },
        { color: "#bd28d7", sample: "Tom3.mp3", keyBoard: "3" },
        { color: "#dc6123", sample: "Cymb.mp3", keyBoard: "q" },
        { color: "#dc6123", sample: "Noise.mp3", keyBoard: "w" },
        { color: "#dc6123", sample: "Open.mp3", keyBoard: "e" },
        { color: "#40db24", sample: "Hat1.mp3", keyBoard: "a" },
        { color: "#40db24", sample: "Hat2.mp3", keyBoard: "s" },
        { color: "#40db24", sample: "Snare2.mp3", keyBoard: "d" },
        { color: "#219dde", sample: "Kick.mp3", keyBoard: "z" },
        { color: "#219dde", sample: "Pre.mp3", keyBoard: "x" },
        { color: "#219dde", sample: "Snare1.mp3", keyBoard: "c" },
      ],
      B: [
        { color: "#bd28d7", sample: "Tom1.mp3", keyBoard: "1" },
        { color: "#bd28d7", sample: "Tom2.mp3", keyBoard: "2" },
        { color: "#bd28d7", sample: "Tom3.mp3", keyBoard: "3" },
        { color: "#dc6123", sample: "Cymb.mp3", keyBoard: "q" },
        { color: "#dc6123", sample: "Roll.mp3", keyBoard: "w" },
        { color: "#dc6123", sample: "Open.mp3", keyBoard: "e" },
        { color: "#40db24", sample: "Hat1.mp3", keyBoard: "a" },
        { color: "#40db24", sample: "Hat2.mp3", keyBoard: "s" },
        { color: "#40db24", sample: "Snare2.mp3", keyBoard: "d" },
        { color: "#219dde", sample: "Kick.mp3", keyBoard: "z" },
        { color: "#219dde", sample: "Pre.mp3", keyBoard: "x" },
        { color: "#219dde", sample: "Snare1.mp3", keyBoard: "c" },
      ],
    },
    Boom_Bap: {
      A: [
        { color: "#bd28d7", sample: "Cymb.mp3", keyBoard: "1" },
        { color: "#bd28d7", sample: "Tamb.mp3", keyBoard: "2" },
        { color: "#bd28d7", sample: "Roll.mp3", keyBoard: "3" },
        { color: "#dc6123", sample: "Rim.mp3", keyBoard: "q" },
        { color: "#dc6123", sample: "Ride.mp3", keyBoard: "w" },
        { color: "#dc6123", sample: "Open.mp3", keyBoard: "e" },
        { color: "#40db24", sample: "Hat1.mp3", keyBoard: "a" },
        { color: "#40db24", sample: "Pre.mp3", keyBoard: "s" },
        { color: "#40db24", sample: "Open.mp3", keyBoard: "d" },
        { color: "#219dde", sample: "Kick.mp3", keyBoard: "z" },
        { color: "#219dde", sample: "Hat1.mp3", keyBoard: "x" },
        { color: "#219dde", sample: "Snare.mp3", keyBoard: "c" },
      ],
      B: [
        { color: "#bd28d7", sample: "Cymb.mp3", keyBoard: "1" },
        { color: "#bd28d7", sample: "Tamb.mp3", keyBoard: "2" },
        { color: "#bd28d7", sample: "Snap.mp3", keyBoard: "3" },
        { color: "#dc6123", sample: "Rim.mp3", keyBoard: "q" },
        { color: "#dc6123", sample: "Ride.mp3", keyBoard: "w" },
        { color: "#dc6123", sample: "Open.mp3", keyBoard: "e" },
        { color: "#40db24", sample: "Hat1.mp3", keyBoard: "a" },
        { color: "#40db24", sample: "Pre.mp3", keyBoard: "s" },
        { color: "#40db24", sample: "Open.mp3", keyBoard: "d" },
        { color: "#219dde", sample: "Kick.mp3", keyBoard: "z" },
        { color: "#219dde", sample: "Hat1.mp3", keyBoard: "x" },
        { color: "#219dde", sample: "Snare.mp3", keyBoard: "c" },
      ],
    },
    Techno: {
      A: [
        { color: "#bd28d7", sample: "Tom1.mp3", keyBoard: "1" },
        { color: "#bd28d7", sample: "Tom2.mp3", keyBoard: "2" },
        { color: "#bd28d7", sample: "Tom3.mp3", keyBoard: "3" },
        { color: "#dc6123", sample: "Cymb.mp3", keyBoard: "q" },
        { color: "#dc6123", sample: "Shaker.mp3", keyBoard: "w" },
        { color: "#dc6123", sample: "Clap.mp3", keyBoard: "e" },
        { color: "#40db24", sample: "Noise1.mp3", keyBoard: "a" },
        { color: "#40db24", sample: "Pre.mp3", keyBoard: "s" },
        { color: "#40db24", sample: "Noise2.mp3", keyBoard: "d" },
        { color: "#219dde", sample: "Kick.mp3", keyBoard: "z" },
        { color: "#219dde", sample: "Hat1.mp3", keyBoard: "x" },
        { color: "#219dde", sample: "Snare.mp3", keyBoard: "c" },
      ],
      B: [
        { color: "#bd28d7", sample: "Perc1.mp3", keyBoard: "1" },
        { color: "#bd28d7", sample: "Perc2.mp3", keyBoard: "2" },
        { color: "#bd28d7", sample: "Perc3.mp3", keyBoard: "3" },
        { color: "#dc6123", sample: "Perc4.mp3", keyBoard: "q" },
        { color: "#dc6123", sample: "Perc5.mp3", keyBoard: "w" },
        { color: "#dc6123", sample: "Perc6.mp3", keyBoard: "e" },
        { color: "#40db24", sample: "Tom.mp3", keyBoard: "a" },
        { color: "#40db24", sample: "Ride.mp3", keyBoard: "s" },
        { color: "#40db24", sample: "Open.mp3", keyBoard: "d" },
        { color: "#219dde", sample: "Kick.mp3", keyBoard: "z" },
        { color: "#219dde", sample: "Hat1.mp3", keyBoard: "x" },
        { color: "#219dde", sample: "Snare.mp3", keyBoard: "c" },
      ],
    },
    UK_Garage: {
      A: [
        { color: "#bd28d7", sample: "Perc1.mp3", keyBoard: "1" },
        { color: "#bd28d7", sample: "Perc2.mp3", keyBoard: "2" },
        { color: "#bd28d7", sample: "Perc3.mp3", keyBoard: "3" },
        { color: "#dc6123", sample: "Perc4.mp3", keyBoard: "q" },
        { color: "#dc6123", sample: "Perc5.mp3", keyBoard: "w" },
        { color: "#dc6123", sample: "Clap.mp3", keyBoard: "e" },
        { color: "#40db24", sample: "Cymb.mp3", keyBoard: "a" },
        { color: "#40db24", sample: "Hat1.mp3", keyBoard: "s" },
        { color: "#40db24", sample: "Clap.mp3", keyBoard: "d" },
        { color: "#219dde", sample: "Kick.mp3", keyBoard: "z" },
        { color: "#219dde", sample: "Pre.mp3", keyBoard: "x" },
        { color: "#219dde", sample: "Snare.mp3", keyBoard: "c" },
      ],
      B: [
        { color: "#bd28d7", sample: "Perc1.mp3", keyBoard: "1" },
        { color: "#bd28d7", sample: "Perc2.mp3", keyBoard: "2" },
        { color: "#bd28d7", sample: "Perc3.mp3", keyBoard: "3" },
        { color: "#dc6123", sample: "Perc4.mp3", keyBoard: "q" },
        { color: "#dc6123", sample: "Tamb.mp3", keyBoard: "w" },
        { color: "#dc6123", sample: "Clap.mp3", keyBoard: "e" },
        { color: "#40db24", sample: "Cymb.mp3", keyBoard: "a" },
        { color: "#40db24", sample: "Hat1.mp3", keyBoard: "s" },
        { color: "#40db24", sample: "Clap.mp3", keyBoard: "d" },
        { color: "#219dde", sample: "Kick.mp3", keyBoard: "z" },
        { color: "#219dde", sample: "Pre.mp3", keyBoard: "x" },
        { color: "#219dde", sample: "Snare.mp3", keyBoard: "c" },
      ],
    },
  },
  Basses: {
    Bass_Guitar: {
      A: [
        { color: "#bd28d7", sample: "Bass C1.mp3", keyBoard: "1" },
        { color: "#bd28d7", sample: "Bass C1d.mp3", keyBoard: "2" },
        { color: "#bd28d7", sample: "Bass D1.mp3", keyBoard: "3" },
        { color: "#dc6123", sample: "Bass D1d.mp3", keyBoard: "q" },
        { color: "#dc6123", sample: "Bass E1.mp3", keyBoard: "w" },
        { color: "#dc6123", sample: "Bass F1.mp3", keyBoard: "e" },
        { color: "#40db24", sample: "Bass F1d.mp3", keyBoard: "a" },
        { color: "#40db24", sample: "Bass G1.mp3", keyBoard: "s" },
        { color: "#40db24", sample: "Bass G1d.mp3", keyBoard: "d" },
        { color: "#219dde", sample: "Bass A1.mp3", keyBoard: "z" },
        { color: "#219dde", sample: "Bass A1d.mp3", keyBoard: "x" },
        { color: "#219dde", sample: "Bass B1.mp3", keyBoard: "c" },
      ],
      B: [
        { color: "#2a30d5", sample: "Bass G1.mp3", keyBoard: "1" },
        { color: "#2a30d5", sample: "Bass G1d.mp3", keyBoard: "2" },
        { color: "#2a30d5", sample: "Bass A1.mp3", keyBoard: "3" },
        { color: "#d52a7f", sample: "Bass A1d.mp3", keyBoard: "q" },
        { color: "#d52a7f", sample: "Bass B1.mp3", keyBoard: "w" },
        { color: "#d52a7f", sample: "Bass C1.mp3", keyBoard: "e" },
        { color: "#d6ce29", sample: "Bass C1d.mp3", keyBoard: "a" },
        { color: "#d6ce29", sample: "Bass D1.mp3", keyBoard: "s" },
        { color: "#d6ce29", sample: "Bass D1d.mp3", keyBoard: "d" },
        { color: "#25da73", sample: "Bass E1.mp3", keyBoard: "z" },
        { color: "#25da73", sample: "Bass F1.mp3", keyBoard: "x" },
        { color: "#25da73", sample: "Bass F1d.mp3", keyBoard: "c" },
      ],
    },
    Chemical_Bass: {
      A: [
        { color: "#bd28d7", sample: "Bass C1.mp3", keyBoard: "1" },
        { color: "#bd28d7", sample: "Bass C1d.mp3", keyBoard: "2" },
        { color: "#bd28d7", sample: "Bass D1.mp3", keyBoard: "3" },
        { color: "#dc6123", sample: "Bass D1d.mp3", keyBoard: "q" },
        { color: "#dc6123", sample: "Bass E1.mp3", keyBoard: "w" },
        { color: "#dc6123", sample: "Bass F1.mp3", keyBoard: "e" },
        { color: "#40db24", sample: "Bass F1d.mp3", keyBoard: "a" },
        { color: "#40db24", sample: "Bass G1.mp3", keyBoard: "s" },
        { color: "#40db24", sample: "Bass G1d.mp3", keyBoard: "d" },
        { color: "#219dde", sample: "Bass A1.mp3", keyBoard: "z" },
        { color: "#219dde", sample: "Bass A1d.mp3", keyBoard: "x" },
        { color: "#219dde", sample: "Bass B1.mp3", keyBoard: "c" },
      ],
      B: [
        { color: "#2a30d5", sample: "Bass G1.mp3", keyBoard: "1" },
        { color: "#2a30d5", sample: "Bass G1d.mp3", keyBoard: "2" },
        { color: "#2a30d5", sample: "Bass A1.mp3", keyBoard: "3" },
        { color: "#d52a7f", sample: "Bass A1d.mp3", keyBoard: "q" },
        { color: "#d52a7f", sample: "Bass B1.mp3", keyBoard: "w" },
        { color: "#d52a7f", sample: "Bass C1.mp3", keyBoard: "e" },
        { color: "#d6ce29", sample: "Bass C1d.mp3", keyBoard: "a" },
        { color: "#d6ce29", sample: "Bass D1.mp3", keyBoard: "s" },
        { color: "#d6ce29", sample: "Bass D1d.mp3", keyBoard: "d" },
        { color: "#25da73", sample: "Bass E1.mp3", keyBoard: "z" },
        { color: "#25da73", sample: "Bass F1.mp3", keyBoard: "x" },
        { color: "#25da73", sample: "Bass F1d.mp3", keyBoard: "c" },
      ],
    },
    Hip_Hop_Bass: {
      A: [
        { color: "#bd28d7", sample: "Bass C1.mp3", keyBoard: "1" },
        { color: "#bd28d7", sample: "Bass C1d.mp3", keyBoard: "2" },
        { color: "#bd28d7", sample: "Bass D1.mp3", keyBoard: "3" },
        { color: "#dc6123", sample: "Bass D1d.mp3", keyBoard: "q" },
        { color: "#dc6123", sample: "Bass E1.mp3", keyBoard: "w" },
        { color: "#dc6123", sample: "Bass F1.mp3", keyBoard: "e" },
        { color: "#40db24", sample: "Bass F1d.mp3", keyBoard: "a" },
        { color: "#40db24", sample: "Bass G1.mp3", keyBoard: "s" },
        { color: "#40db24", sample: "Bass G1d.mp3", keyBoard: "d" },
        { color: "#219dde", sample: "Bass A1.mp3", keyBoard: "z" },
        { color: "#219dde", sample: "Bass A1d.mp3", keyBoard: "x" },
        { color: "#219dde", sample: "Bass B1.mp3", keyBoard: "c" },
      ],
      B: [
        { color: "#2a30d5", sample: "Bass G1.mp3", keyBoard: "1" },
        { color: "#2a30d5", sample: "Bass G1d.mp3", keyBoard: "2" },
        { color: "#2a30d5", sample: "Bass A1.mp3", keyBoard: "3" },
        { color: "#d52a7f", sample: "Bass A1d.mp3", keyBoard: "q" },
        { color: "#d52a7f", sample: "Bass B1.mp3", keyBoard: "w" },
        { color: "#d52a7f", sample: "Bass C1.mp3", keyBoard: "e" },
        { color: "#d6ce29", sample: "Bass C1d.mp3", keyBoard: "a" },
        { color: "#d6ce29", sample: "Bass D1.mp3", keyBoard: "s" },
        { color: "#d6ce29", sample: "Bass D1d.mp3", keyBoard: "d" },
        { color: "#25da73", sample: "Bass E1.mp3", keyBoard: "z" },
        { color: "#25da73", sample: "Bass F1.mp3", keyBoard: "x" },
        { color: "#25da73", sample: "Bass F1d.mp3", keyBoard: "c" },
      ],
    },
    Industrial_Bass: {
      A: [
        { color: "#bd28d7", sample: "Bass C1.mp3", keyBoard: "1" },
        { color: "#bd28d7", sample: "Bass C1d.mp3", keyBoard: "2" },
        { color: "#bd28d7", sample: "Bass D1.mp3", keyBoard: "3" },
        { color: "#dc6123", sample: "Bass D1d.mp3", keyBoard: "q" },
        { color: "#dc6123", sample: "Bass E1.mp3", keyBoard: "w" },
        { color: "#dc6123", sample: "Bass F1.mp3", keyBoard: "e" },
        { color: "#40db24", sample: "Bass F1d.mp3", keyBoard: "a" },
        { color: "#40db24", sample: "Bass G1.mp3", keyBoard: "s" },
        { color: "#40db24", sample: "Bass G1d.mp3", keyBoard: "d" },
        { color: "#219dde", sample: "Bass A1.mp3", keyBoard: "z" },
        { color: "#219dde", sample: "Bass A1d.mp3", keyBoard: "x" },
        { color: "#219dde", sample: "Bass B1.mp3", keyBoard: "c" },
      ],
      B: [
        { color: "#2a30d5", sample: "Bass G1.mp3", keyBoard: "1" },
        { color: "#2a30d5", sample: "Bass G1d.mp3", keyBoard: "2" },
        { color: "#2a30d5", sample: "Bass A1.mp3", keyBoard: "3" },
        { color: "#d52a7f", sample: "Bass A1d.mp3", keyBoard: "q" },
        { color: "#d52a7f", sample: "Bass B1.mp3", keyBoard: "w" },
        { color: "#d52a7f", sample: "Bass C1.mp3", keyBoard: "e" },
        { color: "#d6ce29", sample: "Bass C1d.mp3", keyBoard: "a" },
        { color: "#d6ce29", sample: "Bass D1.mp3", keyBoard: "s" },
        { color: "#d6ce29", sample: "Bass D1d.mp3", keyBoard: "d" },
        { color: "#25da73", sample: "Bass E1.mp3", keyBoard: "z" },
        { color: "#25da73", sample: "Bass F1.mp3", keyBoard: "x" },
        { color: "#25da73", sample: "Bass F1d.mp3", keyBoard: "c" },
      ],
    },
    Sub: {
      A: [
        { color: "#bd28d7", sample: "Bass C1.mp3", keyBoard: "1" },
        { color: "#bd28d7", sample: "Bass C1d.mp3", keyBoard: "2" },
        { color: "#bd28d7", sample: "Bass D1.mp3", keyBoard: "3" },
        { color: "#dc6123", sample: "Bass D1d.mp3", keyBoard: "q" },
        { color: "#dc6123", sample: "Bass E1.mp3", keyBoard: "w" },
        { color: "#dc6123", sample: "Bass F1.mp3", keyBoard: "e" },
        { color: "#40db24", sample: "Bass F1d.mp3", keyBoard: "a" },
        { color: "#40db24", sample: "Bass G1.mp3", keyBoard: "s" },
        { color: "#40db24", sample: "Bass G1d.mp3", keyBoard: "d" },
        { color: "#219dde", sample: "Bass A1.mp3", keyBoard: "z" },
        { color: "#219dde", sample: "Bass A1d.mp3", keyBoard: "x" },
        { color: "#219dde", sample: "Bass B1.mp3", keyBoard: "c" },
      ],
      B: [
        { color: "#2a30d5", sample: "Bass G1.mp3", keyBoard: "1" },
        { color: "#2a30d5", sample: "Bass G1d.mp3", keyBoard: "2" },
        { color: "#2a30d5", sample: "Bass A1.mp3", keyBoard: "3" },
        { color: "#d52a7f", sample: "Bass A1d.mp3", keyBoard: "q" },
        { color: "#d52a7f", sample: "Bass B1.mp3", keyBoard: "w" },
        { color: "#d52a7f", sample: "Bass C1.mp3", keyBoard: "e" },
        { color: "#d6ce29", sample: "Bass C1d.mp3", keyBoard: "a" },
        { color: "#d6ce29", sample: "Bass D1.mp3", keyBoard: "s" },
        { color: "#d6ce29", sample: "Bass D1d.mp3", keyBoard: "d" },
        { color: "#25da73", sample: "Bass E1.mp3", keyBoard: "z" },
        { color: "#25da73", sample: "Bass F1.mp3", keyBoard: "x" },
        { color: "#25da73", sample: "Bass F1d.mp3", keyBoard: "c" },
      ],
    },
  },
  Synths: {
    Crystal: {
      A: [
        { color: "#bd28d7", sample: "Synth C1.mp3", keyBoard: "1" },
        { color: "#bd28d7", sample: "Synth C1d.mp3", keyBoard: "2" },
        { color: "#bd28d7", sample: "Synth D1.mp3", keyBoard: "3" },
        { color: "#dc6123", sample: "Synth D1d.mp3", keyBoard: "q" },
        { color: "#dc6123", sample: "Synth E1.mp3", keyBoard: "w" },
        { color: "#dc6123", sample: "Synth F1.mp3", keyBoard: "e" },
        { color: "#40db24", sample: "Synth F1d.mp3", keyBoard: "a" },
        { color: "#40db24", sample: "Synth G1.mp3", keyBoard: "s" },
        { color: "#40db24", sample: "Synth G1d.mp3", keyBoard: "d" },
        { color: "#219dde", sample: "Synth A1.mp3", keyBoard: "z" },
        { color: "#219dde", sample: "Synth A1d.mp3", keyBoard: "x" },
        { color: "#219dde", sample: "Synth B1.mp3", keyBoard: "c" },
      ],
      B: [
        { color: "#2a30d5", sample: "Synth G1.mp3", keyBoard: "1" },
        { color: "#2a30d5", sample: "Synth G1d.mp3", keyBoard: "2" },
        { color: "#2a30d5", sample: "Synth A1.mp3", keyBoard: "3" },
        { color: "#d52a7f", sample: "Synth A1d.mp3", keyBoard: "q" },
        { color: "#d52a7f", sample: "Synth B1.mp3", keyBoard: "w" },
        { color: "#d52a7f", sample: "Synth C1.mp3", keyBoard: "e" },
        { color: "#d6ce29", sample: "Synth C1d.mp3", keyBoard: "a" },
        { color: "#d6ce29", sample: "Synth D1.mp3", keyBoard: "s" },
        { color: "#d6ce29", sample: "Synth D1d.mp3", keyBoard: "d" },
        { color: "#25da73", sample: "Synth E1.mp3", keyBoard: "z" },
        { color: "#25da73", sample: "Synth F1.mp3", keyBoard: "x" },
        { color: "#25da73", sample: "Synth F1d.mp3", keyBoard: "c" },
      ],
    },
    Luck: {
      A: [
        { color: "#bd28d7", sample: "Synth C1.mp3", keyBoard: "1" },
        { color: "#bd28d7", sample: "Synth C1d.mp3", keyBoard: "2" },
        { color: "#bd28d7", sample: "Synth D1.mp3", keyBoard: "3" },
        { color: "#dc6123", sample: "Synth D1d.mp3", keyBoard: "q" },
        { color: "#dc6123", sample: "Synth E1.mp3", keyBoard: "w" },
        { color: "#dc6123", sample: "Synth F1.mp3", keyBoard: "e" },
        { color: "#40db24", sample: "Synth F1d.mp3", keyBoard: "a" },
        { color: "#40db24", sample: "Synth G1.mp3", keyBoard: "s" },
        { color: "#40db24", sample: "Synth G1d.mp3", keyBoard: "d" },
        { color: "#219dde", sample: "Synth A1.mp3", keyBoard: "z" },
        { color: "#219dde", sample: "Synth A1d.mp3", keyBoard: "x" },
        { color: "#219dde", sample: "Synth B1.mp3", keyBoard: "c" },
      ],
      B: [
        { color: "#2a30d5", sample: "Synth G1.mp3", keyBoard: "1" },
        { color: "#2a30d5", sample: "Synth G1d.mp3", keyBoard: "2" },
        { color: "#2a30d5", sample: "Synth A1.mp3", keyBoard: "3" },
        { color: "#d52a7f", sample: "Synth A1d.mp3", keyBoard: "q" },
        { color: "#d52a7f", sample: "Synth B1.mp3", keyBoard: "w" },
        { color: "#d52a7f", sample: "Synth C1.mp3", keyBoard: "e" },
        { color: "#d6ce29", sample: "Synth C1d.mp3", keyBoard: "a" },
        { color: "#d6ce29", sample: "Synth D1.mp3", keyBoard: "s" },
        { color: "#d6ce29", sample: "Synth D1d.mp3", keyBoard: "d" },
        { color: "#25da73", sample: "Synth E1.mp3", keyBoard: "z" },
        { color: "#25da73", sample: "Synth F1.mp3", keyBoard: "x" },
        { color: "#25da73", sample: "Synth F1d.mp3", keyBoard: "c" },
      ],
    },
    Rhodes: {
      A: [
        { color: "#bd28d7", sample: "Synth C1.mp3", keyBoard: "1" },
        { color: "#bd28d7", sample: "Synth C1d.mp3", keyBoard: "2" },
        { color: "#bd28d7", sample: "Synth D1.mp3", keyBoard: "3" },
        { color: "#dc6123", sample: "Synth D1d.mp3", keyBoard: "q" },
        { color: "#dc6123", sample: "Synth E1.mp3", keyBoard: "w" },
        { color: "#dc6123", sample: "Synth F1.mp3", keyBoard: "e" },
        { color: "#40db24", sample: "Synth F1d.mp3", keyBoard: "a" },
        { color: "#40db24", sample: "Synth G1.mp3", keyBoard: "s" },
        { color: "#40db24", sample: "Synth G1d.mp3", keyBoard: "d" },
        { color: "#219dde", sample: "Synth A1.mp3", keyBoard: "z" },
        { color: "#219dde", sample: "Synth A1d.mp3", keyBoard: "x" },
        { color: "#219dde", sample: "Synth B1.mp3", keyBoard: "c" },
      ],
      B: [
        { color: "#2a30d5", sample: "Synth G1.mp3", keyBoard: "1" },
        { color: "#2a30d5", sample: "Synth G1d.mp3", keyBoard: "2" },
        { color: "#2a30d5", sample: "Synth A1.mp3", keyBoard: "3" },
        { color: "#d52a7f", sample: "Synth A1d.mp3", keyBoard: "q" },
        { color: "#d52a7f", sample: "Synth B1.mp3", keyBoard: "w" },
        { color: "#d52a7f", sample: "Synth C1.mp3", keyBoard: "e" },
        { color: "#d6ce29", sample: "Synth C1d.mp3", keyBoard: "a" },
        { color: "#d6ce29", sample: "Synth D1.mp3", keyBoard: "s" },
        { color: "#d6ce29", sample: "Synth D1d.mp3", keyBoard: "d" },
        { color: "#25da73", sample: "Synth E1.mp3", keyBoard: "z" },
        { color: "#25da73", sample: "Synth F1.mp3", keyBoard: "x" },
        { color: "#25da73", sample: "Synth F1d.mp3", keyBoard: "c" },
      ],
    },
    ShakeString: {
      A: [
        { color: "#bd28d7", sample: "Synth C1.mp3", keyBoard: "1" },
        { color: "#bd28d7", sample: "Synth C1d.mp3", keyBoard: "2" },
        { color: "#bd28d7", sample: "Synth D1.mp3", keyBoard: "3" },
        { color: "#dc6123", sample: "Synth D1d.mp3", keyBoard: "q" },
        { color: "#dc6123", sample: "Synth E1.mp3", keyBoard: "w" },
        { color: "#dc6123", sample: "Synth F1.mp3", keyBoard: "e" },
        { color: "#40db24", sample: "Synth F1d.mp3", keyBoard: "a" },
        { color: "#40db24", sample: "Synth G1.mp3", keyBoard: "s" },
        { color: "#40db24", sample: "Synth G1d.mp3", keyBoard: "d" },
        { color: "#219dde", sample: "Synth A1.mp3", keyBoard: "z" },
        { color: "#219dde", sample: "Synth A1d.mp3", keyBoard: "x" },
        { color: "#219dde", sample: "Synth B1.mp3", keyBoard: "c" },
      ],
      B: [
        { color: "#2a30d5", sample: "Synth G1.mp3", keyBoard: "1" },
        { color: "#2a30d5", sample: "Synth G1d.mp3", keyBoard: "2" },
        { color: "#2a30d5", sample: "Synth A1.mp3", keyBoard: "3" },
        { color: "#d52a7f", sample: "Synth A1d.mp3", keyBoard: "q" },
        { color: "#d52a7f", sample: "Synth B1.mp3", keyBoard: "w" },
        { color: "#d52a7f", sample: "Synth C1.mp3", keyBoard: "e" },
        { color: "#d6ce29", sample: "Synth C1d.mp3", keyBoard: "a" },
        { color: "#d6ce29", sample: "Synth D1.mp3", keyBoard: "s" },
        { color: "#d6ce29", sample: "Synth D1d.mp3", keyBoard: "d" },
        { color: "#25da73", sample: "Synth E1.mp3", keyBoard: "z" },
        { color: "#25da73", sample: "Synth F1.mp3", keyBoard: "x" },
        { color: "#25da73", sample: "Synth F1d.mp3", keyBoard: "c" },
      ],
    },
  },
  Percussion: {
    African_Percussion: {
      A: [
        { color: "#bd28d7", sample: "Conga1.mp3", keyBoard: "1" },
        { color: "#bd28d7", sample: "Conga2.mp3", keyBoard: "2" },
        { color: "#bd28d7", sample: "Conga3.mp3", keyBoard: "3" },
        { color: "#dc6123", sample: "Conga4.mp3", keyBoard: "q" },
        { color: "#dc6123", sample: "Conga5.mp3", keyBoard: "w" },
        { color: "#dc6123", sample: "Conga6.mp3", keyBoard: "e" },
        { color: "#40db24", sample: "Conga7.mp3", keyBoard: "a" },
        { color: "#40db24", sample: "Conga8.mp3", keyBoard: "s" },
        { color: "#40db24", sample: "Conga9.mp3", keyBoard: "d" },
        { color: "#219dde", sample: "Conga10.mp3", keyBoard: "z" },
        { color: "#219dde", sample: "Conga11.mp3", keyBoard: "x" },
        { color: "#219dde", sample: "Conga12.mp3", keyBoard: "c" },
      ],
      B: [
        { color: "#bd28d7", sample: "Djembe1.mp3", keyBoard: "1" },
        { color: "#bd28d7", sample: "Djembe2.mp3", keyBoard: "2" },
        { color: "#bd28d7", sample: "Djembe3.mp3", keyBoard: "3" },
        { color: "#dc6123", sample: "Djembe4.mp3", keyBoard: "q" },
        { color: "#dc6123", sample: "Djembe5.mp3", keyBoard: "w" },
        { color: "#dc6123", sample: "Djembe6.mp3", keyBoard: "e" },
        { color: "#40db24", sample: "Djembe7.mp3", keyBoard: "a" },
        { color: "#40db24", sample: "Djembe8.mp3", keyBoard: "s" },
        { color: "#40db24", sample: "Djembe9.mp3", keyBoard: "d" },
        { color: "#219dde", sample: "Djembe10.mp3", keyBoard: "z" },
        { color: "#219dde", sample: "Djembe11.mp3", keyBoard: "x" },
        { color: "#219dde", sample: "Djembe12.mp3", keyBoard: "c" },
      ],
    },
    CowBell: {
      A: [
        { color: "#bd28d7", sample: "Cow C1.mp3", keyBoard: "1" },
        { color: "#bd28d7", sample: "Cow C1d.mp3", keyBoard: "2" },
        { color: "#bd28d7", sample: "Cow D1.mp3", keyBoard: "3" },
        { color: "#dc6123", sample: "Cow D1d.mp3", keyBoard: "q" },
        { color: "#dc6123", sample: "Cow E1.mp3", keyBoard: "w" },
        { color: "#dc6123", sample: "Cow F1.mp3", keyBoard: "e" },
        { color: "#40db24", sample: "Cow F1d.mp3", keyBoard: "a" },
        { color: "#40db24", sample: "Cow G1.mp3", keyBoard: "s" },
        { color: "#40db24", sample: "Cow G1d.mp3", keyBoard: "d" },
        { color: "#219dde", sample: "Cow A1.mp3", keyBoard: "z" },
        { color: "#219dde", sample: "Cow A1d.mp3", keyBoard: "x" },
        { color: "#219dde", sample: "Cow B1.mp3", keyBoard: "c" },
      ],
      B: [
        { color: "#2a30d5", sample: "Cow G1.mp3", keyBoard: "1" },
        { color: "#2a30d5", sample: "Cow G1d.mp3", keyBoard: "2" },
        { color: "#2a30d5", sample: "Cow A1.mp3", keyBoard: "3" },
        { color: "#d52a7f", sample: "Cow A1d.mp3", keyBoard: "q" },
        { color: "#d52a7f", sample: "Cow B1.mp3", keyBoard: "w" },
        { color: "#d52a7f", sample: "Cow C1.mp3", keyBoard: "e" },
        { color: "#d6ce29", sample: "Cow C1d.mp3", keyBoard: "a" },
        { color: "#d6ce29", sample: "Cow D1.mp3", keyBoard: "s" },
        { color: "#d6ce29", sample: "Cow D1d.mp3", keyBoard: "d" },
        { color: "#25da73", sample: "Cow E1.mp3", keyBoard: "z" },
        { color: "#25da73", sample: "Cow F1.mp3", keyBoard: "x" },
        { color: "#25da73", sample: "Cow F1d.mp3", keyBoard: "c" },
      ],
    },
    Koto: {
      A: [
        { color: "#bd28d7", sample: "Synth C1.mp3", keyBoard: "1" },
        { color: "#bd28d7", sample: "Synth C1d.mp3", keyBoard: "2" },
        { color: "#bd28d7", sample: "Synth D1.mp3", keyBoard: "3" },
        { color: "#dc6123", sample: "Synth D1d.mp3", keyBoard: "q" },
        { color: "#dc6123", sample: "Synth E1.mp3", keyBoard: "w" },
        { color: "#dc6123", sample: "Synth F1.mp3", keyBoard: "e" },
        { color: "#40db24", sample: "Synth F1d.mp3", keyBoard: "a" },
        { color: "#40db24", sample: "Synth G1.mp3", keyBoard: "s" },
        { color: "#40db24", sample: "Synth G1d.mp3", keyBoard: "d" },
        { color: "#219dde", sample: "Synth A1.mp3", keyBoard: "z" },
        { color: "#219dde", sample: "Synth A1d.mp3", keyBoard: "x" },
        { color: "#219dde", sample: "Synth B1.mp3", keyBoard: "c" },
      ],
      B: [
        { color: "#2a30d5", sample: "Synth G1.mp3", keyBoard: "1" },
        { color: "#2a30d5", sample: "Synth G1d.mp3", keyBoard: "2" },
        { color: "#2a30d5", sample: "Synth A1.mp3", keyBoard: "3" },
        { color: "#d52a7f", sample: "Synth A1d.mp3", keyBoard: "q" },
        { color: "#d52a7f", sample: "Synth B1.mp3", keyBoard: "w" },
        { color: "#d52a7f", sample: "Synth C1.mp3", keyBoard: "e" },
        { color: "#d6ce29", sample: "Synth C1d.mp3", keyBoard: "a" },
        { color: "#d6ce29", sample: "Synth D1.mp3", keyBoard: "s" },
        { color: "#d6ce29", sample: "Synth D1d.mp3", keyBoard: "d" },
        { color: "#25da73", sample: "Synth E1.mp3", keyBoard: "z" },
        { color: "#25da73", sample: "Synth F1.mp3", keyBoard: "x" },
        { color: "#25da73", sample: "Synth F1d.mp3", keyBoard: "c" },
      ],
    },
    Xylophone: {
      A: [
        { color: "#bd28d7", sample: "Xylo C1.mp3", keyBoard: "1" },
        { color: "#bd28d7", sample: "Xylo C1d.mp3", keyBoard: "2" },
        { color: "#bd28d7", sample: "Xylo D1.mp3", keyBoard: "3" },
        { color: "#dc6123", sample: "Xylo D1d.mp3", keyBoard: "q" },
        { color: "#dc6123", sample: "Xylo E1.mp3", keyBoard: "w" },
        { color: "#dc6123", sample: "Xylo F1.mp3", keyBoard: "e" },
        { color: "#40db24", sample: "Xylo F1d.mp3", keyBoard: "a" },
        { color: "#40db24", sample: "Xylo G1.mp3", keyBoard: "s" },
        { color: "#40db24", sample: "Xylo G1d.mp3", keyBoard: "d" },
        { color: "#219dde", sample: "Xylo A1.mp3", keyBoard: "z" },
        { color: "#219dde", sample: "Xylo A1d.mp3", keyBoard: "x" },
        { color: "#219dde", sample: "Xylo B1.mp3", keyBoard: "c" },
      ],
      B: [
        { color: "#bd28d7", sample: "Xylo C1.mp3", keyBoard: "1" },
        { color: "#bd28d7", sample: "Xylo C1d.mp3", keyBoard: "2" },
        { color: "#bd28d7", sample: "Xylo E1.mp3", keyBoard: "3" },
        { color: "#dc6123", sample: "Xylo F1.mp3", keyBoard: "q" },
        { color: "#dc6123", sample: "Xylo F1d.mp3", keyBoard: "w" },
        { color: "#dc6123", sample: "Xylo G1d.mp3", keyBoard: "e" },
        { color: "#40db24", sample: "Xylo B1.mp3", keyBoard: "a" },
        { color: "#40db24", sample: "Xylo C2.mp3", keyBoard: "s" },
        { color: "#40db24", sample: "Xylo C2d.mp3", keyBoard: "d" },
        { color: "#219dde", sample: "Xylo E2.mp3", keyBoard: "z" },
        { color: "#219dde", sample: "Xylo F2.mp3", keyBoard: "x" },
        { color: "#219dde", sample: "Xylo F2d.mp3", keyBoard: "c" },
      ],
    },
  },
};
